FROM golang:1.23-alpine as builder

WORKDIR /app

COPY backend ./

RUN go mod tidy && go build -o app

FROM alpine:latest

WORKDIR /app

RUN apk --no-cache add ca-certificates

COPY --from=builder /app/main /app/main

ENV PORT=${PORT}

CMD ["/app/main"]